development:
  dialect: mysql
  database: buffalo_api_development
  user: root
  password: mysql
  host: 127.0.0.1
  pool: 5

test:
  dialect: mysql
  database: buffalo_api_test
  user: root
  password: mysql
  host: 127.0.0.1
  pool: 5
